spring:
  application:
    name: mcp-client-app
  ai:
    mcp:
      client:
        sse:
          connections:
            server1:
              url: http://localhost:8081
            server2:
              url: http://localhost:8082
server:
  port: 8080
